Feature to add a vec/array slice of permissions instead of having to add every single permission
nbry/smartcar-rust-sdk pull request #14
Opened 2023-05-28 17:51 UTC by ehuff700

Title is pretty self-explanatory, this PR is more inline with the officially supported Smartcar SDK's and allows for neater code. Also cleaned up some unnecessary code to meet clippy warnings.

2023-05-30 16:37 UTC, nbry requested changes
Thank you for your contribution to this repo. I really like the changes you put in, I just request that you do not remove the `add_permission` method in this PR.

2023-06-03 23:46 UTC, ehuff700 commented on src/error.rs
> +    SmartcarError(Box<SmartcarError>),
In cases of large error types (like the SmartcarError) it is beneficial to Box the error. Boxing an error allocates memory on the heap vs. the stack which improves performance for large error types. Without boxing the error the compiler has to allocate the memory for the size of the Err variant every single time. Since a Box is a pointer that owns a heap allocation, the size of the Err variant is lessened **significantly**. See [this resource](https://rust-lang.github.io/rust-clippy/master/index.html#/result_large_err) for a full breakdown.

2023-06-03 23:46 UTC, ehuff700 commented on src/lib.rs
> +    pub fn add_permissions<T>(mut self, permissions: T) -> Self where T: AsRef<[Permission]> {
Good point, latest commit should resolve this problem.

2023-06-05 17:09 UTC, nbry approved these changes
Changes look good to me! Feel free to Squash and Merge whenever you're ready. Also don't worry about the build failures right now; I am working separately on fixing the test issues.

Right now the crate publishing is manual, so I'll take care of it when I have some free time.

Thank you @ehuff007!

2023-06-08 01:16 UTC, ehuff700 commented
@nbry commit history was squashed, you'll have to merge as I don't have write access

2023-06-08 05:13 UTC, merged

2023-06-08 16:47 UTC, nbry commented
@ehuff700 Again, thank you for your contributions!

Your changes are available in the last two releases of the crate.